Exec Verify_CategoriesRow 2, 'Arts', '', 'Arts', NULL, '', '', 'Arts'
Exec Verify_CategoriesRow 3, 'Business', '', 'Business', NULL, 'Business, finance, enterprise', 'A listing of some great business sites, as well as the latest business news.', 'Business Information' 
Exec Verify_CategoriesRow 4, 'Computers', '', 'Computers', NULL, '', '', 'Computers'
Exec Verify_CategoriesRow 5, 'Games', '', 'Games', NULL, '', '', 'Games'
Exec Verify_CategoriesRow 6, 'Health', '', 'Health', NULL, '', '', 'Health'
Exec Verify_CategoriesRow 7, 'Home', '', 'Home', NULL, '', '', 'Home'
Exec Verify_CategoriesRow 8, 'Kids and Teens', '', 'Kids and Teens', NULL, '', '', 'Kids and Teens'
Exec Verify_CategoriesRow 9, 'News', '', 'News', NULL, '', '', 'News'
Exec Verify_CategoriesRow 10, 'Recreation', '', 'Recreation', NULL, '', '', 'Recreation'
Exec Verify_CategoriesRow 11, 'Reference', '', 'Reference', NULL, '', '', 'Reference'
Exec Verify_CategoriesRow 12, 'Regional', '', 'Regional', NULL, '', '', 'Regional'
Exec Verify_CategoriesRow 13, 'Science', '', 'Science', NULL, '', '', 'Science'

Exec Verify_CategoriesRow 14, 'Shopping', '', 'Shopping', NULL, '', '', 'Shopping'
Exec Verify_CategoriesRow 15, 'Society', '', 'Society', NULL, '', '', 'Society'
Exec Verify_CategoriesRow 16, 'Sports', '', 'Sports', NULL, '', '', 'Sports'
Exec Verify_CategoriesRow 17, 'Television', '', 'Television', 2, '', '', 'Television'
Exec Verify_CategoriesRow 18, 'Music', '', 'Music', 2, '', '', 'Music'
Exec Verify_CategoriesRow 19, 'Jobs', '', 'Jobs', 3, '', '', 'Jobs'
Exec Verify_CategoriesRow 20, 'Real Estate', '', 'Real Estate', 3, '', '', 'Real-Estate'
Exec Verify_CategoriesRow 21, 'Investing', '', 'Investing', 3, '', '', 'Investing'
Exec Verify_CategoriesRow 22, 'Internet', '', 'Internet', 4, '', '', 'Internet'
Exec Verify_CategoriesRow 23, 'Software', '', 'Software', 4, '', '', 'Software'

Exec Verify_CategoriesRow 24, 'Hardware', '', 'Hardware', 4, '', '', 'Hardware'
Exec Verify_CategoriesRow 25, 'Video Games', '', 'Video Games', 5, '', '', 'Video Games'
Exec Verify_CategoriesRow 26, 'RPGs', '', 'RPGs', 5, '', '', 'RPGs'
Exec Verify_CategoriesRow 27, 'Gambling', '', 'Gambling', 5, '', '', 'Gambling'
Exec Verify_CategoriesRow 28, 'Fitness', '', 'Fitness', 6, '', '', 'Fitness'
Exec Verify_CategoriesRow 29, 'Medicine', '', 'Medicine', 6, '', '', 'Medicine'
Exec Verify_CategoriesRow 30, 'Alternative', '', 'Alternative', 6, '', '', 'Alternative'
Exec Verify_CategoriesRow 31, 'Family', '', 'Family', 7, '', '', 'Family'
Exec Verify_CategoriesRow 32, 'Consumers', '', 'Consumers', 7, '', '', 'Consumers'
Exec Verify_CategoriesRow 33, 'Cooking', '', 'Cooking', 7, '', '', 'Cooking'

Exec Verify_CategoriesRow 34, 'Arts', '', 'Arts2', 8, '', '', 'Arts2'
Exec Verify_CategoriesRow 35, 'School Time', '', 'School Time', 8, '', '', 'School Time'
Exec Verify_CategoriesRow 36, 'Teen Life', '', 'Teen-Life', 8, '', '', 'Teen-Life'
Exec Verify_CategoriesRow 37, 'Media', '', 'Media', 9, '', '', 'Media'
Exec Verify_CategoriesRow 38, 'Newspapers', '', 'Newspapers', 9, '', '', 'Newspapers'
Exec Verify_CategoriesRow 39, 'Weather', '', 'Weather', 9, '', '', 'Weather'
Exec Verify_CategoriesRow 40, 'Travel', '', 'Travel', 10, '', '', 'Travel'
Exec Verify_CategoriesRow 41, 'Food', '', 'Food', 10, '', '', 'Food'
Exec Verify_CategoriesRow 42, 'Outdoors', '', 'Outdoors', 10, '', '', 'Outdoors'
Exec Verify_CategoriesRow 43, 'Humor', '', 'Humor', 10, '', '', 'Humor'

Exec Verify_CategoriesRow 44, 'Maps', '', 'Maps', 11, '', '', 'Maps'
Exec Verify_CategoriesRow 45, 'Education', '', 'Education', 11, '', '', 'Education'
Exec Verify_CategoriesRow 46, 'Libraries', '', 'Libraries', 11, '', '', 'Libraries'
Exec Verify_CategoriesRow 47, 'United States', '', 'United States', 12, '', '', 'United States'
Exec Verify_CategoriesRow 48, 'Canada', '', 'Canada', 12, '', '', 'Canada'
Exec Verify_CategoriesRow 49, 'United Kingdom', '', 'United-Kingdom', 12, '', '', 'United Kingdom'
Exec Verify_CategoriesRow 50, 'Europe', '', 'Europe', 12, '', '', 'Europe'
Exec Verify_CategoriesRow 51, 'Biology', '', 'Biology', 13, '', '', 'Biology'
Exec Verify_CategoriesRow 52, 'Psychology', '', 'Psychology', 13, '', '', 'Psychology'
Exec Verify_CategoriesRow 53, 'Physics', '', 'Physics', 13, '', '', 'Physics'

Exec Verify_CategoriesRow 54, 'Autos', '', 'Autos', 14, '', '', 'Autos'
Exec Verify_CategoriesRow 55, 'Clothing', '', 'Clothing', 14, '', '', 'Clothing'
Exec Verify_CategoriesRow 56, 'Gifts', '', 'Gifts', 14, '', '', 'Gifts'
Exec Verify_CategoriesRow 57, 'People', '', 'People', 15, '', '', 'Society & People'
Exec Verify_CategoriesRow 58, 'Religion', '', 'Religion', 15, '', '', 'Religion'
Exec Verify_CategoriesRow 59, 'Issues', '', 'Issues', 15, '', '', 'Issues'
Exec Verify_CategoriesRow 60, 'Baseball', '', 'Baseball', 16, '', '', 'Baseball'
Exec Verify_CategoriesRow 61, 'Soccer', '', 'Soccer', 16, '', '', 'Soccer'
Exec Verify_CategoriesRow 62, 'Basketball', '', 'Basketball', 16, '', '', 'Basketball'
Exec Verify_CategoriesRow 71, 'Movies', '', 'Movies', 2, '', '', 'Movies'
Exec Verify_CategoriesRow 72, 'World', '', 'World', NULL, '', '', 'World'
Exec Verify_CategoriesRow 73, 'Insurance', '', 'Insurance', NULL, 'insurance, auto insurance, health insurance, life insurance', 'A listing of respectable insurance businesses, and the latest news in insurance.', 'Insurance Information'



/* 
select * from categories

*/