<%@ Reference Page="~/members/link-page-design/linkpagepreview.aspx" %>

<%@ Page Language="c#" Inherits="Nle.Website.Members.Link_Page_Design.LinkPageDesignDefault"
    ValidateRequest="false" CodeFile="Default.aspx.cs" MasterPageFile="~/MasterPage.master" %>

<%@ Register TagPrefix="Nle" Namespace="Nle.Website.Common_Controls" %>
<%@ Reference Control="~/Common_Controls/StatusHeader.ascx" %>
<asp:Content runat="Server" ContentPlaceHolderID="mainContent">

    <script language="JavaScript" type="text/javascript" src="<%= Nle.Website.Global.VirtualDirectory %>Scripts/DynamicHelp.js"></script>

    <script>
			var DEFAULT_TEMPLATE = "<asp:Literal Runat="server" ID="litDefaultTemplate" />";
			var LINK_PAGE_SOURCE_CLIENTID = "<asp:Literal Runat="server" ID="litPageSourceClientId" />";

			function LoadDefaultTemplate()
			{
				var sourceCode = document.getElementById(LINK_PAGE_SOURCE_CLIENTID);
				sourceCode.value = DEFAULT_TEMPLATE;
			}
    </script>

    <asp:PlaceHolder runat="server" ID="controlplaceholder" />
    <Nle:DynamicHelp ID="dynamicHelp" runat="Server">
		<nle:DynamicHelpText runat="server" ID="dhtSourceToolbarTitle" HelpId="1" Title="Insert {title} Tag Button" Text="<p><b>Title</b> Used in the &lt; head &gt; section of the page. For example: &lt; title &gt; {title} &lt; /title &gt; </p>" />
		<nle:DynamicHelpText runat="server" ID="dhtSourceToolbarMetaKeywords" HelpId="2" Title="Insert {metaKeywords} Tag Button" Text="<p><b>Meta Keywords</b> Used in the &lt;head&gt; section of the page to specify the key content of the page. For example: <meta name=&quote;keywords&quote; content=&quote;{metaKeywords}&quote;/> </p>" />
		<nle:DynamicHelpText runat="server" ID="dhtSourceToolbarMetaDescrition" HelpId="3" Title="Insert {metaDescription} Tag Button" Text="<p><b>Meta Description</b> Used in the &lt;head&gt; section of the page to describe the page. For example: <meta name=&quote;description&quote; content=&quote;{metaDescription}&quote;/></p>" />
		<nle:DynamicHelpText runat="server" ID="dhtSourceToolbarCategories" HelpId="4" Title="Insert {relatedCategories} Tag Button" Text="<p><b>Categories</b> The section that will be the links to the categories that your site is related to.</p>" />
		<nle:DynamicHelpText runat="server" ID="dhtSourceToolbarRSSFeeds" HelpId="5" Title="Insert {rssFeeds} Tag Button" Text="<p><b>Article Feeds</b> The section that will be the content generated by the RSS feed.</p>" />
		<nle:DynamicHelpText runat="server" ID="dhtSourceToolbarArticles" HelpId="6" Title="Insert {articles} Tag Button" Text="<p><b>Articles</b> The section that will be the articles linking to other members' sites.</p>" />
		<nle:DynamicHelpText runat="server" ID="dhtSourceEditor" HelpId="7" Title="Source Code Editor" Text="<p>Use this area to edit your source code manually.  Use the tabs at the bottom to switch between preview mode and source editing mode so you can preview an example of what your preview will look like once it has been generated.</p>" />
		<nle:DynamicHelpText runat="server" ID="dhtSourceEditorTabs" HelpId="8" Title="Source Code Editor Modes" Text="<p>Switch the source code editor between modes.</p><p><b>Source</b> Edit the source code.</p><p><b>Preview</b> See an example of what your link page will look like based off of the source code that you have entered.</p>" />
		<nle:DynamicHelpText runat="server" ID="dhtDefaultTemplate" HelpId="9" Title="Default Template" Text="<p>Click to reset the text in the source code editor to the default template source code.</p>" />
		<nle:DynamicHelpText runat="server" ID="dhtSiteSelector" HelpId="999" Title="Site Selector" Text="<p>Use the Site Selector to easily switch between sites to configure that site.</p>" />
    </Nle:DynamicHelp>
    <h1>
        Link Page Designer</h1>
    <div class="StepText">
        <asp:Panel runat="server" ID="pnlNoWizard">
            <p>
                Welcome to the Link Page Designer. You must create this link page template so NaturalLinkExchange
                can place the links from other sites on your site. You will not receive links until
                your link page is configured, installed on your site and working. Using this tool
                is like using a word processor mail merge. You simply set up the way you want your
                pages to look like you would a letter in a mail merge. Then you place the tokens
                in the template. When NaturalLinkExchange generates the pages for your site, it
                replaces these tokens with the appropriate HTML. You must include all 6 tokens in
                order to save this template. The <b>{Title}</b>, <b>{Metakeywords}</b> & <b>{MetaDescription}</b>
                tokens need to go in the &lt;HEAD&gt; section of your HTML page. The remaining tokens,
                <b>{relatedCategories}</b>, <b>{articles}</b> & <b>{rssFeeds}</b> need to go in
                the &lt;BODY&gt; section of your HTML page. We have provided convenient buttons
                to insert these tokens or you can simply type them in. Use the Preview button to
                see an example of what your page will look like. Don't worry about making a mistake,
                you can always start over by going back to the Control Panel and selecting the Article
                Page Template Wizard again. If you have questions or problems please <a id="A3" runat="server"
                    href="~/Support/">contact us by opening a support case</a>.
            </p>
        </asp:Panel>
        <asp:Panel runat="server" ID="pnlWizardStep1">
            <p>
                <asp:Image ID="Image3" runat="server" ImageUrl="~/Images/step3.gif" CssClass="StepImage" />The
                final step of the wizard is to modify the HTML below by placing special tokens where
                they belong. Using this tool is like using a word processor mail merge. You simply
                set up the way you want your pages to look like you would a letter in a mail merge.
                Then you place the tokens in the template. The wizard has already added some of
                the tokens like <b>{Title}</b>, <b>{Metakeywords}</b> & <b>{MetaDescription}</b>
                that go in the &lt;HEAD&gt; section of your HTML page. The remaining tokens, <b>{relatedCategories}</b>,
                <b>{articles}</b> & <b>{rssFeeds}</b> need to go in the &lt;BODY&gt; section of
                your HTML page. When NaturalLinkExchange generates the pages for your site, it replaces
                these tokens with the appropriate HTML. Carefully choose a place to put each of
                the remaining tokens and then click the button associated with the appropriate one
                to insert it or you can simply type in the token. Click the Preview button to see
                what your page will look like. Don't worry about making a mistake, you can always
                start over by going back to the Control Panel and selecting the Article Page Template
                Wizard again. If you have questions or problems please <a id="A1" runat="server"
                    href="~/Support/">contact us by opening a support case</a>.
            </p>
        </asp:Panel>
        <p>
            The <b>{relatedCategories}</b> token will be replaced by links to other pages
            that will have content that is related to your particular topic. Most of the time
            you want to place this just above or just below the {articles} token. The
            <b>{articles}</b> token will be replaced by actual content in the form of
            articles and links that other webmasters submitted for their sites. As the content,
            this is the meat of the page so you will want to place it in a prominent position
            like you would one of your own articles. The <b>{rssFeeds}</b> token will
            be replaced by fresh and changing content. Place this on your page in a less important
            position like an "in other news" position maybe on the bottom of the page.
        </p>
        <asp:Panel runat="server" ID="pnlWizardStep2">
            <p>
                That's it! You have completed the template for your site. There's just one more
                Control Panel configuration item that needs to be performed. Just return to the
                Control Panel and select the way you want us to generate pages from this template.</p>
        </asp:Panel>
        <p>
            Problems or questions? Check out our video on <a id="A4" runat="server" href="~/Videos/Editing Your Link Page.htm">
                Creating Your Template</a> as well as <a id="A5" runat="server" href="~/Videos/">other
                    helpful videos</a>. If you still need help please <a id="A2" runat="server" href="~/Support/">
                        contact us by opening a support case.</a>
        </p>
    </div>
    <div class="LinkPageSource">
        <div class="Toolbars">
            <asp:Panel runat="server" ID="sourceToolbar">
                <asp:Button runat="server" ID="txtInsertText" Text="Title" onmouseout="return HideDynamicHelp('dynamicHelp');"
                    onmouseover="return ShowDynamicHelp('dynamicHelp', 1)" CssClass="SourceCodeButton" /><asp:Button
                        ID="txtInsertMetaKeywords" runat="server" Text="Meta Keywords" onmouseout="return HideDynamicHelp('dynamicHelp');"
                        onmouseover="return ShowDynamicHelp('dynamicHelp', 2)" CssClass="SourceCodeButton" /><asp:Button
                            ID="txtInsertMetaDescription" runat="server" Text="Meta Description" onmouseout="return HideDynamicHelp('dynamicHelp');"
                            onmouseover="return ShowDynamicHelp('dynamicHelp', 3)" CssClass="SourceCodeButton" /><asp:Button
                                ID="txtInsertCategories" runat="server" Text="Categories" onmouseout="return HideDynamicHelp('dynamicHelp');"
                                onmouseover="return ShowDynamicHelp('dynamicHelp', 4)" CssClass="SourceCodeButton" /><asp:Button
                                    ID="txtInsertRssFeeds" runat="server" Text="RSS Feeds" onmouseout="return HideDynamicHelp('dynamicHelp');"
                                    onmouseover="return ShowDynamicHelp('dynamicHelp', 5)" CssClass="SourceCodeButton" /><asp:Button
                                        ID="txtInsertArticles" runat="server" Text="Articles" onmouseout="return HideDynamicHelp('dynamicHelp');"
                                        onmouseover="return ShowDynamicHelp('dynamicHelp', 6)" CssClass="SourceCodeButton" /><br />
            </asp:Panel>
        </div>
        Link Page Source:
        <div onmouseout="return HideDynamicHelp('dynamicHelp');" onmouseover="return ShowDynamicHelp('dynamicHelp', 7);">
            <asp:PlaceHolder runat="server" ID="previewPlaceholder" />
        </div>
        <asp:Label ID="lblMissingTokens" runat="server" CssClass="MissingTokens" Visible="false" />
        <asp:TextBox runat="server" ID="txtLinkPageSource" TextMode="MultiLine" Rows="10"
            onmouseout="return HideDynamicHelp('dynamicHelp');" onmouseover="return ShowDynamicHelp('dynamicHelp', 7);" />
        <div class="Tabs" onmouseout="return HideDynamicHelp('dynamicHelp');" onmouseover="return ShowDynamicHelp('dynamicHelp', 8);">
            <asp:Button runat="server" ID="cmdPreview" Text="Preview" /><asp:Button runat="server"
                ID="cmdSource" Text="Source" />
        </div>
    </div>
    <input type="button" value="Load Default Template" onclick="LoadDefaultTemplate();"
        onmouseout="return HideDynamicHelp('dynamicHelp');" onmouseover="return ShowDynamicHelp('dynamicHelp', 9);" />
    <asp:Button runat="server" ID="cmdSave" Text="Save" />
    <asp:Button runat="server" ID="cmdCancel" Text="Cancel" /><br />
    <asp:PlaceHolder runat="server" ID="javaScriptPlaceholder" />
</asp:Content>
